[package]
name = "wae-macros"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
repository = "https://github.com/raftario/wae.git"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
darling = "0.12"
quote = "1.0"
syn = "1.0"
